### ISSUE TITLE
The difference between online and offline version

### ISSUE THREAD

**Issue by Zhangjiacheng144** [hikvision-research/SSOD#14]
Hi, Thanks for such great work! I noticed that you implemented the offline ACT by the `labelmatch_hooks`, but in the configs of the online version, there still exists the 'LabelMatchHook'  config. I wonder if this config of `LabelMatchHook` needs to be deleted in the online version. More precisely, to delete the part about evaluating with the unlabeled data and then update the threshold.

**Comment by AceCoooool** [comment]
The `LabelMatchHook` is only used as initialization in online version. (The `update_interval = total_iter + 1` in online version)

**Comment by AceCoooool** [comment]
The `LabelMatchHook` is only used as initialization in online version. (The `update_interval = total_iter + 1` in online version)

**Comment by Zhangjiacheng144** [comment]
But the "LabelMatchHook" seems also exists in the config of the offline version, is there any difference?

**Comment by AceCoooool** [comment]
offline: we use the `LabelMatchHook` to update our thresholds every 1000 iters.
online: the `LabelMatchHook` only used before training to get the inital thresholds.
`update_interval` means the interval to call this `LabelMatchHook`.
